alias chrome="app ${DIR[APPS]}/Google\ Chrome.app"
alias discord/stable="app ${DIR[APPS]}/Discord.app"
alias discord/canary="app ${DIR[APPS]}/Discord\ Secondary.app"
alias gband="app ${DIR[APPS]}/GarageBand.app"
alias gsync="app ${DIR[APPS]}/Backup\ and\ Sync.app"
alias logi="app ${DIR[APPS]}/Logi\ Options.app"
alias mc="app ${DIR[APPS]}/Minecraft.app"

alias at="app ${DIR[PWA]}/Audiotool\ Studio.app"
alias devdocs="app ${DIR[PWA]}/DevDocs.app"
alias ig="app ${DIR[PWA]}/Instagram.app"
alias toh="app ${DIR[PWA]}/Tower\ of\ Hanoi.app"
alias twitter="app ${DIR[PWA]}/Twitter.app"
alias photos="app ${DIR[PWA]}/Google\ Photos.app"
alias messages="app ${DIR[PWA]}/Messages.app"

alias booster="java -jar ~/.audiotool/launcher.jar"
