#!/usr/bin/env python3
from argparse import ArgumentParser

"""
`<FTName | lowercase>` command
"""

def get_cli_args():
    """Process the provided command-line arguments and return a valid
    Namespace for the CLI
    """

    parser = ArgumentParser(description="")

    parser.add_argument()

    return parser.parse_args()


if __name__ == "__main__":
    ns = get_cli_args()
