#!/bin/zsh
# DEST:~/.zshrc

# Environment constants...

# An associative array of common directories
# accessed like "${DIR[KEY]}"
declare -xrA DIR=(
  # Applications
  [APPS]=/Applications
  [PWAS]=~/Applications/Chrome\ Apps.localized

  # Documents
  [DESK]=~/Desktop
  [DLS]=~/Downloads
  [DOCS]=~/Documents

  # Developer Modules
  [DEV]=~/Developer
  [DOTF]=~/projects/dotfiles
  [SHM]=~/projects/dotfiles/src
  [SHB]=~/projects/dotfiles/src/bin
  [SHS]=~/projects/dotfiles/src/scripts
)

# Paths, etc.
export PATH=${DIR[APPS]}/Visual\ Studio\ Code.app/Contents/Resources/app/bin:$PATH
export PATH=/opt/homebrew/opt/openjdk@17/bin:$PATH
export PATH=/opt/homebrew/opt/openjdk/bin:$PATH

export EDITOR="code --wait"
export SSH_AUTH_SOCK=~/.1password/agent.sock

# Conditional setup...
# Allows for multi-device usage where some utilities are not available
# or configured in the same way as other devices

# homebrew (latest)
local BREW_EXEC=/opt/homebrew/bin/brew
if [[ -x $BREW_EXEC ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# 1password
if mdfind -name kMDItemFSName=="1Password.app" | grep . &>/dev/null; then
  local OP_DIR=~/.1password
  if ! [[ -d $OP_DIR ]]; then
    mkdir $OP_DIR
    ln -s ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock $OP_DIR/agent.sock
  fi

  export SSH_AUTH_SOCK=$OP_DIR/agent.sock

  local OP_PLUGINS=~/.config/op/plugins.sh
  if [[ -e $OP_PLUGINS ]]; then
    source $OP_PLUGINS
  fi
fi

# direnv
if which direnv &>/dev/null; then
  eval "$(direnv hook zsh)"

  # we provide our own initial logs
  export DIRENV_LOG_FORMAT=""
fi

# nvm
export NVM_DIR=~/.nvm
if ! [[ -d $NVM_DIR ]]; then
  mkdir $NVM_DIR
fi

local NVM_OPT=/opt/homebrew/opt/nvm
# This loads nvm
[ -s "$NVM_OPT/nvm.sh" ] && source $NVM_OPT/nvm.sh
# This loads nvm bash_completion
[ -s "$NVM_OPT/etc/bash_completion.d/nvm" ] && source $NVM_OPT/etc/bash_completion.d/nvm

# oh-my-zsh
local OMZ_DIR=~/.oh-my-zsh
if [[ -d $OMZ_DIR ]]; then
  export ZSH=$OMZ_DIR
  source ${DIR[DOTF]}/oh-my-zsh/preferences.zsh
fi

# pyenv
local PYENV_ROOT=~/.pyenv
if [[ -d $PYENV_ROOT/bin ]]; then
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
fi

# Source customizations...

# Ensure all files in "src/bin" are executable
for bin in $(find ${DIR[SHB]} -type f -not -name "*.*"); do
  if [[ ! -x $bin ]]; then
    chmod +x $bin
  fi
done
export PATH=${DIR[SHB]}:$PATH

# Source all custom functions, aliases, etc.
for module in $(find ${DIR[SHM]} -type f -name "*.zsh"); do
  # Added a conditional to ignore certain files w/ designator
  if [[ ! $(head -2 $module) =~ "^# SOURCE-IGNORE$" ]]; then
    source $module
  fi
done

# pnpm
export PNPM_HOME="/Users/lewx/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# android
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true
