name: 🚀 Create new release on GitHub
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: |
          bun install
          bun run build
          echo "dotfiles=dist/dotfiles" >> $GITHUB_ENV

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create v$($dotfiles --version) $dotfiles --generate-notes
